version: '3'

services:
  postgres:
    container_name: mfcs_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - './env/.env.dev.db'       
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mfcs_net 
    restart: unless-stopped
    healthcheck:
        test: pg_isready -U postgres -h postgres
        interval: 30s
        timeout: 3s
        retries: 3                

  redis:
    image: redis:alpine
    container_name: mfcs_redis
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - mfcs_net
    restart: unless-stopped  
    healthcheck:
      test: redis-cli -h redis ping
      interval: 30s
      timeout: 3s
      retries: 3               

  mfcs_ruby: 
    build: 
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    container_name: mfcs_ruby
    command: bash -c "rm -f tmp/pids/server.pid ; rm -rf tmp/cache ; bundle exec rails s -p 3000 -b 0.0.0.0"
    env_file:
      - './env/.env.dev.mfcs'        
    volumes:
      - .:/home/mfcs:cached
      - rails_cache_data:/app/tmp/cache
      - bundle_data:/usr/local/bundle
      - node_modules_data:/home/mfcs/node_modules
      - packs_data:/app/public/packs
      - mfcs_tmp:/home/mfcs/tmp
      - mfcs_storage:/home/mfcs/storage
      - ./importing:/home/mfcs/importing

      #- mfcs-data:/home/mfcs/data     
    ports:
      - "3000:3000" 
      - "3001:3001"
    links:
      - 'postgres'
      - 'redis'
      # - 'elasticsearch'
      - 'webpacker'
    networks:
      - mfcs_net
    tmpfs:
      - /tmp
    restart: unless-stopped        
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 30s
      timeout: 3s
      retries: 3                                          

  sidekiq:
    container_name: mfcs_sidekiq
    links:
      - 'postgres'
      - 'redis'
    build: 
      context: ./
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file:
      - './env/.env.dev.mfcs'      
    restart: always      
    volumes:
      - ./:/home/mfcs:cached
      - rails_cache_data:/app/tmp/cache
      - bundle_data:/usr/local/bundle  
      - mfcs_tmp:/home/mfcs/tmp
      - mfcs_storage:/home/mfcs/storage          
    networks:
      - mfcs_net
    depends_on:
      - postgres
      - redis         

  webpacker:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: mfcs_webpack
    env_file:
      - './env/.env.dev.webpacker'
    command: bundle exec ./bin/webpack-dev-server --inline true
    volumes:
      - .:/home/mfcs:cached
      - bundle_data:/usr/local/bundle
      - node_modules_data:/home/mfcs/node_modules
      - packs_data:/app/public/packs      
    ports:
      - '3035:3035'
    networks:
      - mfcs_net      

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
  #   container_name: mfcs_elasticsearch
  #   restart: always
  #   # env_file:
  #   #   - './env/.env.es'  
  #   environment:
  #     - "discovery.type=single-node"
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"           
  #   volumes: 
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   healthcheck:
  #     interval: 10s
  #     retries: 80
  #     test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/    
  #   ports: 
  #     - 9200:9200
  #     - 9300:9300   
  #   networks:
  #     - mfcs_net

volumes:
  rails_cache_data:
  bundle_data:
  node_modules_data:
  packs_data:
  redis:
  postgres:
  elasticsearch:
  mfcs_tmp:
  mfcs_storage:
  
  #mfcs-data:

networks:
  mfcs_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mfcs

