 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/items/digital_objects", type: :request do
  # Items::DigitalObject. As you add validations to Items::DigitalObject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Items::DigitalObject.create! valid_attributes
      get items_digital_objects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      digital_object = Items::DigitalObject.create! valid_attributes
      get items_digital_object_url(items_digital_object)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_items_digital_object_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      digital_object = Items::DigitalObject.create! valid_attributes
      get edit_items_digital_object_url(items_digital_object)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Items::DigitalObject" do
        expect {
          post items_digital_objects_url, params: { items_digital_object: valid_attributes }
        }.to change(Items::DigitalObject, :count).by(1)
      end

      it "redirects to the created items_digital_object" do
        post items_digital_objects_url, params: { items_digital_object: valid_attributes }
        expect(response).to redirect_to(items_digital_object_url(@items_digital_object))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Items::DigitalObject" do
        expect {
          post items_digital_objects_url, params: { items_digital_object: invalid_attributes }
        }.to change(Items::DigitalObject, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post items_digital_objects_url, params: { items_digital_object: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested items_digital_object" do
        digital_object = Items::DigitalObject.create! valid_attributes
        patch items_digital_object_url(items_digital_object), params: { items_digital_object: new_attributes }
        digital_object.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the items_digital_object" do
        digital_object = Items::DigitalObject.create! valid_attributes
        patch items_digital_object_url(items_digital_object), params: { items_digital_object: new_attributes }
        digital_object.reload
        expect(response).to redirect_to(items_digital_object_url(digital_object))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        digital_object = Items::DigitalObject.create! valid_attributes
        patch items_digital_object_url(items_digital_object), params: { items_digital_object: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested items_digital_object" do
      digital_object = Items::DigitalObject.create! valid_attributes
      expect {
        delete items_digital_object_url(items_digital_object)
      }.to change(Items::DigitalObject, :count).by(-1)
    end

    it "redirects to the items_digital_objects list" do
      digital_object = Items::DigitalObject.create! valid_attributes
      delete items_digital_object_url(items_digital_object)
      expect(response).to redirect_to(items_digital_objects_url)
    end
  end
end
