 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/items/metadata", type: :request do
  # Items::Metadatum. As you add validations to Items::Metadatum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Items::Metadatum.create! valid_attributes
      get items_metadata_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      metadatum = Items::Metadatum.create! valid_attributes
      get items_metadatum_url(items_metadatum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_items_metadatum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      metadatum = Items::Metadatum.create! valid_attributes
      get edit_items_metadatum_url(items_metadatum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Items::Metadatum" do
        expect {
          post items_metadata_url, params: { items_metadatum: valid_attributes }
        }.to change(Items::Metadatum, :count).by(1)
      end

      it "redirects to the created items_metadatum" do
        post items_metadata_url, params: { items_metadatum: valid_attributes }
        expect(response).to redirect_to(items_metadatum_url(@items_metadatum))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Items::Metadatum" do
        expect {
          post items_metadata_url, params: { items_metadatum: invalid_attributes }
        }.to change(Items::Metadatum, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post items_metadata_url, params: { items_metadatum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested items_metadatum" do
        metadatum = Items::Metadatum.create! valid_attributes
        patch items_metadatum_url(items_metadatum), params: { items_metadatum: new_attributes }
        metadatum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the items_metadatum" do
        metadatum = Items::Metadatum.create! valid_attributes
        patch items_metadatum_url(items_metadatum), params: { items_metadatum: new_attributes }
        metadatum.reload
        expect(response).to redirect_to(items_metadatum_url(metadatum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        metadatum = Items::Metadatum.create! valid_attributes
        patch items_metadatum_url(items_metadatum), params: { items_metadatum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested items_metadatum" do
      metadatum = Items::Metadatum.create! valid_attributes
      expect {
        delete items_metadatum_url(items_metadatum)
      }.to change(Items::Metadatum, :count).by(-1)
    end

    it "redirects to the items_metadata list" do
      metadatum = Items::Metadatum.create! valid_attributes
      delete items_metadatum_url(items_metadatum)
      expect(response).to redirect_to(items_metadata_url)
    end
  end
end
