 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/permissions", type: :request do
  # Permission. As you add validations to Permission, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Permission.create! valid_attributes
      get admin_permissions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      permission = Permission.create! valid_attributes
      get admin_permission_url(permission)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_permission_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      permission = Permission.create! valid_attributes
      get edit_admin_permission_url(permission)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Permission" do
        expect {
          post admin_permissions_url, params: { admin_permission: valid_attributes }
        }.to change(Permission, :count).by(1)
      end

      it "redirects to the created admin_permission" do
        post admin_permissions_url, params: { admin_permission: valid_attributes }
        expect(response).to redirect_to(admin_permission_url(Permission.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Permission" do
        expect {
          post admin_permissions_url, params: { admin_permission: invalid_attributes }
        }.to change(Permission, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_permissions_url, params: { admin_permission: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested admin_permission" do
        permission = Permission.create! valid_attributes
        patch admin_permission_url(permission), params: { permission: new_attributes }
        permission.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the admin_permission" do
        permission = Permission.create! valid_attributes
        patch admin_permission_url(permission), params: { permission: new_attributes }
        permission.reload
        expect(response).to redirect_to(permission_url(permission))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        permission = Permission.create! valid_attributes
        patch admin_permission_url(permission), params: { permission: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_permission" do
      permission = Permission.create! valid_attributes
      expect {
        delete admin_permission_url(permission)
      }.to change(Permission, :count).by(-1)
    end

    it "redirects to the permissions list" do
      permission = Permission.create! valid_attributes
      delete admin_permission_url(permission)
      expect(response).to redirect_to(admin_permissions_url)
    end
  end
end
