development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_SIDEKIQ") { "redis://mfcs_redis:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_SIDEKIQ") { "redis://mfcs_redis:6379/1" } %>
  channel_prefix: mfcs_production