default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: mfcs_db
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: mfcs_dev
  
test:
  <<: *default
  database: mfcs_test

production:
  <<: *default
  database: mfcs
  username: mfcs_user
  password: <%= ENV['DATABASE_PASSWORD'] %>