import PurgeKeys from "form_builder/purge_keys.js";

/**
 * 
 * ============================================================================
*/
describe("PureKeys_IDNO", ()=> { 
  let idno_json = {
    "field_id":"3589821000001393",
    "type":"idno",
    "name":"idno",
    "label":"Identifier",
    "value":"",
    "placeholder":"",
    "css_id":"sdfklhjadsff ",
    "css_class":"as;dflkjasdf asdfl;kjasd ",
    "sort_order":"1",
    "local_styles":"",
    "metadata_standards":"[{\"schema\":\"Dublin Core\",\"identifier\":\"test\",\"qualifier\":\"something\"},{\"schema\":\"Dublin Core\",\"identifier\":\"testing \",\"qualifier\":\"somethingcooler\"},{\"schema\":\"Dublin Core\",\"identifier\":\"id\",\"qualifier\":\"qualifier\"}]",
    "schema":"Dublin Core",
    "identifier":"id",
    "qualifier":"qualifier",
    "help_type":"",
    "help_url":"",
    "help_info":"",
    "managed_by":"System",
    "idno_format":"test_#####",
    "start_increment":"1",
    "min":"",
    "max":"",
    "format":"",
    "step":"",
    "min_number":"",
    "max_number":"",
    "choice_type":"",
    "default_choice":"",
    "choice_array":"",
    "choices":"",
    "choice_form":"",
    "choice_form_field":"",
    "allowed_file_types":"",
    "extension":"",
    "multiple_files":false,
    "combine":false,
    "ocr":false,
    "convert":false,
    "thumbnail":false,
    "watermark":false,
    "border":false,
    "convert_audio":false,
    "convert_video":false,
    "video_thumbnail":false,
    "image_height":"",
    "image_width":"",
    "image_resolution":"",
    "image_format":"",
    "thumbnail_height":"",
    "thumbnail_width":"",
    "thumbnail_resolution":"",
    "thumbnail_format":"",
    "border_height":"",
    "border_width":"",
    "watermark_image":"",
    "watermark_location":"",
    "audio_bitrate":"",
    "audio_format":"",
    "video_bitrate":"",
    "video_format":"",
    "video_height":"",
    "video_width":"",
    "video_thumbnail_height":"",
    "video_thumbnail_width":"",
    "video_thumbnail_frames":"",
    "video_thumbnail_format":"",
    "required":true,
    "no_duplicates":false,
    "read_only":false,
    "disabled":false,
    "disabled_on_insert":false,
    "disabled_on_update":false,
    "public_release":true,
    "oai_release":true,
    "sortable":true,
    "searchable":true,
    "display_in_list":true,
    "hidden":false,
    "validation":"",
    "validation_regex":""
  }
  let purge = PurgeKeys.new('idno', idno_json); 
  purge.delete_keys

});